#!/usr/bin/env fish
# logseq-session-hook.fish - Auto-log session summary to Logseq
# Runs on SessionEnd. Never blocks (exit 0 always).

cd "$CLAUDE_PROJECT_DIR" 2>/dev/null || cd (pwd)

set -l LOGSEQ_BASE "/home/feanor/Documents/plans and ideas/pages/brain-dumps"
set -l TIMESTAMP (date +%Y-%m-%d-%H%M)
set -l DATE (date +%Y-%m-%d)
set -l PROJECT_NAME (basename (pwd))
set -l LOGSEQ_PAGE "$LOGSEQ_BASE/$PROJECT_NAME-session-$TIMESTAMP.md"

if not test -d "$LOGSEQ_BASE"
    echo "WARNING: Logseq directory not found: $LOGSEQ_BASE"
    exit 0
end

echo "=========================================="
echo "  SESSION LOGGING (Logseq)"
echo "=========================================="
echo ""

# Get git changes
set -l GIT_CHANGES ""
if git diff --stat 2>/dev/null | tail -5 > /dev/null
    set GIT_CHANGES (git diff --stat 2>/dev/null | tail -5)
end

# Get tool commands
set -l TOOL_COMMANDS ""
if test -f "$CLAUDE_PROJECT_DIR/.claude/terminal-history.log"
    set TOOL_COMMANDS (grep -E "magellan|llmgrep|mirage|splice" "$CLAUDE_PROJECT_DIR/.claude/terminal-history.log" 2>/dev/null | tail -20)
end

# Write session file
echo "---" > "$LOGSEQ_PAGE"
echo "title: $PROJECT_NAME Session $TIMESTAMP" >> "$LOGSEQ_PAGE"
echo "tags: [$PROJECT_NAME, session, llm-coded]" >> "$LOGSEQ_PAGE"
echo "date: $DATE" >> "$LOGSEQ_PAGE"
echo "---" >> "$LOGSEQ_PAGE"
echo "" >> "$LOGSEQ_PAGE"
echo "# Session Summary" >> "$LOGSEQ_PAGE"
echo "" >> "$LOGSEQ_PAGE"
echo "**Project:** $PROJECT_NAME" >> "$LOGSEQ_PAGE"
echo "**Date:** $DATE" >> "$LOGSEQ_PAGE"
echo "" >> "$LOGSEQ_PAGE"
echo "## Changes Made" >> "$LOGSEQ_PAGE"
echo "" >> "$LOGSEQ_PAGE"

if test -n "$GIT_CHANGES"
    echo '```' >> "$LOGSEQ_PAGE"
    echo "$GIT_CHANGES" >> "$LOGSEQ_PAGE"
    echo '```' >> "$LOGSEQ_PAGE"
else
    echo "*No git changes*" >> "$LOGSEQ_PAGE"
end

echo "" >> "$LOGSEQ_PAGE"
echo "## Tool Commands" >> "$LOGSEQ_PAGE"
echo "" >> "$LOGSEQ_PAGE"

if test -n "$TOOL_COMMANDS"
    echo '```bash' >> "$LOGSEQ_PAGE"
    echo "$TOOL_COMMANDS" >> "$LOGSEQ_PAGE"
    echo '```' >> "$LOGSEQ_PAGE"
else
    echo "*No commands logged*" >> "$LOGSEQ_PAGE"
end

echo "" >> "$LOGSEQ_PAGE"
echo "## Hooks" >> "$LOGSEQ_PAGE"
echo "- query-schema-check" >> "$LOGSEQ_PAGE"
echo "- query-symbol-check" >> "$LOGSEQ_PAGE"
echo "- verify-rust" >> "$LOGSEQ_PAGE"
echo "- splice-cycles-check" >> "$LOGSEQ_PAGE"
echo "- stub-check" >> "$LOGSEQ_PAGE"
echo "- wiring-check" >> "$LOGSEQ_PAGE"
echo "" >> "$LOGSEQ_PAGE"
echo "## Checklist" >> "$LOGSEQ_PAGE"
echo "- [ ] cargo check passed" >> "$LOGSEQ_PAGE"
echo "- [ ] splice cycles clean" >> "$LOGSEQ_PAGE"
echo "" >> "$LOGSEQ_PAGE"
echo "## Notes" >> "$LOGSEQ_PAGE"
echo "" >> "$LOGSEQ_PAGE"
echo "*Auto-generated by logseq-session-hook.fish*" >> "$LOGSEQ_PAGE"

echo "  Session logged: $LOGSEQ_PAGE"
echo ""

exit 0
